In [4]:
import torch

scores = torch.tensor([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
print(scores[:,-1:])
mask = torch.tensor([[1, 0, 0]])
scores= scores.unsqueeze(0).unsqueeze(0)
print(scores)
scores = scores.masked_fill(mask == 0, -1e9)
print(scores)
e = torch.empty(0, 3)
f = torch.ones(1, 3)
g = torch.cat((e, f), dim=0)
print(e.shape)
print(g)

tensor([[0.3000],
        [0.6000],
        [0.9000]])
tensor([[[[0.1000, 0.2000, 0.3000],
          [0.4000, 0.5000, 0.6000],
          [0.7000, 0.8000, 0.9000]]]])
tensor([[[[ 1.0000e-01, -1.0000e+09, -1.0000e+09],
          [ 4.0000e-01, -1.0000e+09, -1.0000e+09],
          [ 7.0000e-01, -1.0000e+09, -1.0000e+09]]]])
torch.Size([0, 3])
tensor([[1., 1., 1.]])


In [1]:
import torch
from transformer import Bert, Transformer
vocab_size = 1024
seq = arr = torch.tensor([[1,1,1,1,0,0,0],[1,1,1,0,0,0,0]])
dec = torch.tensor([[1,1,1,0,0,0],[1,1,0,0,0,0]])
logits = Bert.BERT(vocab_size=vocab_size,num_heads=2,num_layers=1)(seq)
print(logits.shape)
model = Transformer.Transformer(1024,1024,num_heads=2,num_layers=1)
output, logitss = model(seq,dec)
print(logitss.shape)
print(logitss)

torch.Size([2, 7, 768])
torch.Size([2, 6, 768])
tensor([[[-0.6045,  1.3061,  1.8412,  ...,  1.4684, -0.3996,  0.9207],
         [ 0.3479,  0.7857,  2.6157,  ...,  1.3424, -0.6106,  1.2924],
         [ 0.2968, -0.2764,  2.9504,  ...,  1.8682, -0.7492,  1.3036],
         [ 0.3244,  0.3033,  0.7407,  ...,  1.8151, -0.2391,  2.2699],
         [-0.4322,  0.4339, -0.1183,  ...,  1.6096, -0.3874,  2.3086],
         [-0.7347,  1.4958, -0.8436,  ...,  1.6217, -0.1354,  2.4185]],

        [[-0.0915,  1.6476,  1.9834,  ...,  0.6351, -0.1314,  1.3702],
         [ 0.1282,  0.9600,  2.6880,  ...,  0.9991, -0.7791,  0.9617],
         [ 1.0561,  0.4818,  1.5933,  ...,  0.9836,  0.0146,  2.3497],
         [ 0.2164,  0.2182,  0.3952,  ...,  1.2688,  0.1375,  2.4563],
         [-0.5478,  0.3075, -0.5693,  ...,  1.2885,  0.0537,  2.2451],
         [-1.1079,  1.4365, -0.4291,  ...,  1.3681, -0.0697,  2.0996]]],
       grad_fn=<AddBackward0>)


In [1]:
import torch
vocab_size = 1024
seq = arr = torch.tensor([[2,3,4,5,0,0,0],[1,2,3,0,0,0,0]])
dec = torch.tensor([[1],[1]])
model = Transformer.Transformer(1024,1024,num_heads=2,num_layers=3)
model.eval()
#output, logitss = model(seq,dec)
for i in range(10):
    logits, _ = model(seq,dec)
    pred = torch.softmax(logits[:,-1,:],dim=-1)
    next_token = torch.argmax(pred,dim=-1)
    dec = torch.cat([dec,next_token.unsqueeze(1)],dim=-1)
print(dec)

tensor([[  1, 493, 425, 579, 320, 152, 627, 148, 425, 261, 841],
        [  1, 535, 227, 576, 284, 841, 460, 676, 980, 261, 980]])


In [2]:
model.initial_cache(True)
model.eval()
dec = torch.tensor([[1],[1]])
for i in range(10):
    logits, _ = model(seq,dec)
    pred = torch.softmax(logits[:,-1,:],dim=-1)
    next_token = torch.argmax(pred,dim=-1)
    dec = torch.cat([dec,next_token.unsqueeze(1)],dim=-1)
print(dec)
model.clear_cache()

tensor([[  1, 493,  86, 414, 841, 718, 294, 841, 214, 425, 882],
        [  1, 535, 568, 980, 535, 568, 754, 261, 980, 535, 568]])


In [5]:
model.remove_cache()
model.eval()
dec = torch.tensor([[1],[1]])
for i in range(10):
    logits, _ = model(seq,dec)
    pred = torch.softmax(logits[:,-1,:],dim=-1)
    next_token = torch.argmax(pred,dim=-1)
    dec = torch.cat([dec,next_token.unsqueeze(1)],dim=-1)
print(dec)

tensor([[  1, 493, 425, 579, 320, 152, 627, 148, 425, 261, 841],
        [  1, 535, 227, 576, 284, 841, 460, 676, 980, 261, 980]])


In [12]:
def revise(list4=None):
    if list4[0] is None:
        list4[0] = [1,1,1]
    return 0

def revise2(list1):
    revise(list1["a"])
    print(list1)
    return 0

def revise3(list2):
    revise2(list2[0])
    return 0

a = [{"a":[None,1]}]
revise3(a)
print(a)
cache= [
                {"self_attn":[
                    None, None
                ],
                "enc_attn":[
                    None, None
                ]
                }
                for _ in range(3)]
print(cache)

{'a': [[1, 1, 1], 1]}
[{'a': [[1, 1, 1], 1]}]
[{'self_attn': [None, None], 'enc_attn': [None, None]}, {'self_attn': [None, None], 'enc_attn': [None, None]}, {'self_attn': [None, None], 'enc_attn': [None, None]}]


In [ ]:
import torch
vocab_size = 1024
seq = arr = torch.tensor([[1,1,1,1,0,0,0],[1,1,1,0,0,0,0]])
dec = torch.tensor([[1],[1]])
model = Transformer.Transformer(1024,1024,num_heads=2,num_layers=2)
#output, logitss = model(seq,dec)
for i in range(10):
    logits, _ = model(seq,dec)
    pred = torch.softmax(logits[:,-1,:],dim=-1)
    next_token = torch.argmax(pred,dim=-1)
    dec = torch.cat([dec,next_token.unsqueeze(1)],dim=-1)
print(dec)

tensor([[   1,   95, 1014,  816,  377,  272,  219,  983,   90, 1014,  816],
        [   1,   95, 1014,  349,  219,  351,  123,  478,  830,  478,  830]])
